### ISSUE TITLE
Research for Funnel 1

### ISSUE THREAD

**Issue by danlessa** [BlockScience/scf-module-library-docs#12]
- [x] Describe channels where community can express desires
- [x] First check on any expressions of desires

**Comment by jackhack00** [comment]
Describe channels where community can express desires
- Channeling from less to more formal
    - Anywhere (No requirements): Twitter, conferences etc. 
    - Discord (Discord Channel Requirements)
        - Potentially Separate Discord Channel on existing Stellar Discord?
        - Benefit is ease of onboarding, existing credentials, ease of use
        - Downside is SCF control? 
    - GML Form (GML Funnel Requirements)
        - Separate Page On Gitbook, accessible to all, with maintainers as reviewers before adding to actual backlog

General Workflow for expressing desires:
* Community Member (CM) realizes potential idea
* (Optional) CM brings idea to Discord to guage interest (minimum requirements for description)
* CM brings idea into funnel requirements by submitting via form
* Maintainer checks requests and accepts / denies based on whether requirements were kept, not based on liking/interest
* If accepted, form submission is channeled onto "Funnel 1" on Gitbook and removed from "pending". If denied, form submission is removed from "pending" and submitter is notified that requirements were not kept. 

Requirements Ideation:
Brief Summary of Idea/Desire
Brief explanation why / for what it could be useful
Category: Power Attribution, Signalling Form, Reputation Metrics, Identity Management, "NEW"

First check on any expressions of desires
    - Checked: Discord, Twitter, Reddit
    - Discord wanted to see more of NQG but did not express any specific desires. 
    - Otherwise no expressions
