### ISSUE TITLE
Draft Description for Funnel 1: tracking the community desires for modules

### ISSUE THREAD

**Issue by danlessa** [BlockScience/scf-module-library-docs#7]

**Comment by danlessa** [comment]
A/C: Funnel is described according to the form in #11

**Comment by jackhack00** [comment]
## Funnel 1: Tracking the community desires for modules
Funnel 1 allows contributors to minimally describe desires for modules. It consists of a GML form, which anyone can use to input. This form describes the minimum information needed to be accepted into the first backlog. Form inputs are minimally reviewed by maintainers based on the minimum information being present, not on subjective interest or high quality. 

1. Funnel State
* Inputs (Sources eg. "backlog")
    * Human Input
* Outputs (Sinks, or Resolution Options, eg "done", "won't do", "invalid")
    * Desire Backlog
* Intermediate states (eg. labels, for instance: "marked for dev", "blocked", "review", etc)
    * Submitted -> Pending -> In Review -> Resolved (Accepted / Denied / Needs additional information)
2. Roles
    * Community Contributor: 
        * Can be anyone
        * Can access the form (might need Gitbook login)
        * Can input desires
    * Maintainer: 
        * Qualified Role
        * Reviews inputs and accepts/rejects them to first backlog 
4. Processes
TODO: Minimum Information needed for acceptance
TODO: Format of Input Form
TODO: Maintainer Role and authorization
    1. A contributor can fill in a form on a new module they desire
    2. A maintainer can check the pending desires
    3. A maintainer can review the pending desires
    4. A maintainer can resolve the pending desires.
        i. Accept -> Moved to desire backlog + Removed from Funnel 1
        ii. Deny -> Removed from Funnel 1
        iii. Additional information needed -> Contributor notified
