### ISSUE TITLE
Draft Description for Funnel 2: mapping desires into actionable R&D stories

### ISSUE THREAD

**Issue by danlessa** [BlockScience/scf-module-library-docs#8]

**Comment by danlessa** [comment]
A/C: Funnel is described according to the form in #11

**Comment by jackhack00** [comment]
## Funnel 2: Mapping desires into actionable R&D stories
Funnel 2 allows to track all backlogged desires, and allows community contributors to add additional information as well as define actionable R&D stories

1. Funnel State
* Inputs (Sources eg. "backlog")
    * Desire Backlog
* Outputs (Sinks, or Resolution Options, eg "done", "won't do", "invalid")
    * R&D Backlog
        * With (empty) stories
* Intermediate states (eg. labels, for instance: "marked for dev", "blocked", "review", etc)
    * No stories described
    * Some stories described, without min. reached
    * Min. Stories described, not yet moved onwards
2. Roles
    * Community Contributor:
        * Can be anyone.
        * Can see current desire backlog.
        * Can describe stories for R&D.
        * Can add additional information to backlogged desire.
    * Maintainer:
        * Qualified Role
        * Can review described stories.
            * Accept / Deny / Request additional information
        * Can review additional information to backlogged desire.
        * Can move backlogged desire to next funnel if x / y stories are described.
