### ISSUE TITLE
Draft Description for funnel 3: development of prioritized modules for R&D

### ISSUE THREAD

**Issue by danlessa** [BlockScience/scf-module-library-docs#9]

**Comment by danlessa** [comment]
A/C: Funnel is described according to the form in #11

**Comment by jackhack00** [comment]
## Funnel 3: Development of prioritized modules for R&D
Funnel 3 allows to track the R&D backlog and lets contributors develop the described stories. 


1. Funnel State
* Inputs (Sources eg. "backlog")
    * R&D Backlog
* Outputs (Sinks, or Resolution Options, eg "done", "won't do", "invalid")
    * GML
* Intermediate states (eg. labels, for instance: "marked for dev", "blocked", "review", etc)
    * 0% of stories completed
    * Min % of stories completed
        * Might be specific types of stories that are needed for moving onwards
    * Stories completed, unreviewed
    * Stories reviewed, but Module not ready to be moved into GML yet
    * Completed, ready to be moved
2. Roles
    * Community Contributor:
        * Can be anyone.
        * Can see current R&D backlog.
        * Can develop stories for R&D.
        * Can request moving to GML.
    * Maintainer:
        * Qualified Role
        * Can review developed stories.
            * Accept / Deny / Request additional information
        * Can move module into GML if qualifying criteria for developed stories is reached. 
4. Processes
TODO: Types of Stories needed (A/C)
TODO: Who should be able to develop / review?
TODO: Prioritization 
TODO: Bounties

    1. A contributor can see the described stories
    2. A contributor can develop described R&D stories and propose them
    3. A maintainer can review developed R&D stories and accept / deny 
    4. A maintainer can move a module with min. stories developed from R&D backlog into GML.
